### ISSUE TITLE
get_if_addrs doesn't support iface with both v4 and v6 IP

### ISSUE THREAD

**Issue by hfiguiere** [maidsafe/get_if_addrs#19]
get_if_addrs doesn't support iface with both v4 and v6 IP

https://github.com/maidsafe/get_if_addrs/blob/master/src/lib.rs#L58 show that Interface::addr is an IfAddr which is an enum of V4 / V6. So I don't see how we can have both IPv4 and IPv6 in the same interface.

**Comment by dirvine** [comment]
We should be supporting v4 and v6, which can sit easily on the same interface. Or am I misunderstanding your point here? (sry if I am)

**Comment by hfiguiere** [comment]
Oh I see, I didn't read far enough the code. It list me a second interface with the same name with the IPv6 address. I was hoping it have something like

``` rust
pub struct Interface {
    pub name: String,
    pub addr: IfAddr,
}
pub struct IfAddr {
    /// This is an Ipv4 interface.
    pub v4: Option<Ifv4Addr>,
    /// This is an Ipv6 interface.
    pub v6: Option<Ifv6Addr>,
}
```

At least I can work around with this.
