### ISSUE TITLE
GPL license in deps

### ISSUE THREAD

**Issue by kpp** [maidsafe/get_if_addrs#44]
There are deps with GPL license:

* c_linked_list
* get_if_addrs-sys

Please fix it

**Comment by kpp** [comment]
@Viv-Rajkumar You relicensed get_if_addrs-sys, but you forgot to publish the new version to crates.io. See https://crates.io/crates/get_if_addrs-sys

**Comment by S-Coyle** [comment]
@kpp Thanks for flagging this to us!
We've requested that the owner of c_linked_list publishes a new version to crates.io, then we can do the same with get_if_addrs-sys.
Should hopefully be done in the next day or so

**Comment by S-Coyle** [comment]
@kpp Now updated. Thanks
